// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzaxtfxpsytelqpglwxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6YXh0Znhwc3l0ZWxxcGdsd3h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MjkyMTQsImV4cCI6MjA3OTIwNTIxNH0.rKlFLIlgAkNMXLNnPcKmWC0kVAzdqsDRJWGme7ebrJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});